# Generated by Django 1.11.29 on 2020-09-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_solutions_organizations', '0006_auto_20181012_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='additional_metadata',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='organization',
            name='salesforce_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
