# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-24 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_solutions_organizations', '0007_auto_20200908_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistedUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
            ],
        ),
    ]
