# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-24 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edx_solutions_organizations', '0008_whitelistedurls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whitelistedurls',
            options={'verbose_name_plural': 'Whitelisted Urls'},
        ),
    ]
