# Generated by Django 2.2.16 on 2021-05-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_solutions_organizations', '0009_auto_20201224_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_redirected_to_docebo',
            field=models.BooleanField(default=False),
        ),
    ]
