# Generated by Django 2.2.16 on 2021-05-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_solutions_organizations', '0009_auto_20201224_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='docebo_redirect_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='docebo_sso_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='migrated_to_docebo',
            field=models.BooleanField(default=False),
        ),
    ]
