# Generated by Django 2.2.16 on 2021-11-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_solutions_organizations', '0010_auto_20210505_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationusersattributes',
            name='is_main_company',
            field=models.BooleanField(default=False),
        ),
    ]
