# Generated by Django 2.2.16 on 2021-05-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_solutions_organizations', '0010_organization_is_redirected_to_docebo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
