# Generated by Django 2.2.16 on 2021-10-16 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edx_solutions_organizations', '0011_organizationusermapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationusermapping',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_organizations', to='edx_solutions_organizations.Organization'),
        ),
        migrations.AlterField(
            model_name='organizationusermapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_organizations', to=settings.AUTH_USER_MODEL),
        ),
    ]
